from enum import IntEnum


class DisconnectReason(IntEnum):
    CONNECTION_CLOSED = 428
    CONNECTION_LOST = 408
    CONNECTION_REPLACED = 440
    TIMED_OUT = 408
    LOGGED_OUT = 401
    BAD_SESSION = 500
    RESTART_REQUIRED = 515
    MULTIDEVICE_MISMATCH = 411
    FORBIDDEN = 403
    UNAVAILABLE_SERVICE = 503
